Process Process-6:
Traceback (most recent call last):
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "controller.py", line 173, in slave_routine
    r_gen = RolloutGenerator(logdir, device, time_limit)
  File "controller.py", line 57, in __init__
    for fname in (vae_file, rnn_file)]
  File "controller.py", line 57, in <listcomp>
    for fname in (vae_file, rnn_file)]
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 536, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 400, in restore_location
    return default_restore_location(storage, location)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/serialization.py", line 99, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/torch/cuda/__init__.py", line 615, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
